{
 "title": "Instat PL Dashboard",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Coal Price in €/kWh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€/kWh" } },
   "targets": [
    {
     "dataset": "opendata",
     "rawSql": "SELECT $__timeGroup(date,$__interval), AVG(price_eur_per_kwh) FROM instrat_pl.coal_price WHERE $__timeFilter(date) GROUP BY $__timeGroup(date, $__interval) ORDER BY $__timeGroup(date, $__interval) "
    }
   ]
  },
  {
   "title": "CO2 price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "€/t CO2eq" } },
   "targets": [
    {
     "dataset": "opendata",
     "rawSql": "SELECT\n  $__timeGroup(date, $__interval),\n  AVG(eur_per_tco2)\nFROM\n  instrat_pl.eu_ets\nWHERE\n  $__timeFilter(date)\nGROUP BY\n  1"
    }
   ]
  },
  {
   "title": "Gas price in €/kWh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "€/kWh" } },
   "targets": [
    {
     "dataset": "opendata",
     "rawSql": "SELECT\n  $__timeGroup(date, $__interval),\n  AVG(price_eur_per_kwh)\nFROM\n  instrat_pl.gas_price\nWHERE\n  $__timeFilter(date)\nGROUP BY\n  1"
    }
   ]
  }
 ]
}