{
 "title": "smard",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Stromerzeugung SMARD (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "dataset": "opendata",
     "rawSql": "SELECT \n$__timeGroupAlias(datum_von,$__interval),\nAVG(\"biomasse_[mwh]_berechnete_auflösungen\") AS \"biomasse\",\nAVG(\"wasserkraft_[mwh]_berechnete_auflösungen\") AS \"wasserkraft\",\nAVG(\"wind_offshore_[mwh]_berechnete_auflösungen\") AS \"wind_offshore\",\nAVG(\"wind_onshore_[mwh]_berechnete_auflösungen\") AS \"wind_onshore\",\nAVG(\"photovoltaik_[mwh]_berechnete_auflösungen\") AS \"photovoltaik\",\nAVG(\"sonstige_erneuerbare_[mwh]_berechnete_auflösungen\") AS \"sonstige_erneuerbare\",\nAVG(\"kernenergie_[mwh]_berechnete_auflösungen\") AS \"kernenergie\",\nAVG(\"braunkohle_[mwh]_berechnete_auflösungen\") AS \"braunkohle\",\nAVG(\"steinkohle_[mwh]_berechnete_auflösungen\") AS \"steinkohle\",\nAVG(\"erdgas_[mwh]_berechnete_auflösungen\") AS \"erdgas\",\nAVG(\"pumpspeicher_[mwh]_berechnete_auflösungen\") AS \"pumpspeicher\",\nAVG(\"sonstige_konventionelle_[mwh]_berechnete_auflösungen\") AS \"sonstige_konventionelle\"\nFROM smard.generation \nWHERE $__timeFilter(datum_von)\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Import & Export",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "dataset": "opendata",
     "rawSql": "SELECT $__timeGroup(datum_von,$__interval), AVG(\"niederlande_(export)_[mwh]_berechnete_auflösungen\") AS \"niederlande_export\", AVG(\"niederlande_(import)_[mwh]_berechnete_auflösungen\") AS \"niederlande_import\", AVG(\"schweiz_(export)_[mwh]_berechnete_auflösungen\") AS \"schweiz_export\", AVG(\"schweiz_(import)_[mwh]_berechnete_auflösungen\") AS \"schweiz_import\", AVG(\"tschechien_(import)_[mwh]_berechnete_auflösungen\") AS \"tschechien_import\", AVG(\"luxemburg_(export)_[mwh]_berechnete_auflösungen\") AS \"lu_export\", AVG(\"luxemburg_(import)_[mwh]_berechnete_auflösungen\") AS \"lu_import\", AVG(\"österreich_(export)_[mwh]_berechnete_auflösungen\") AS \"österreich_export\", AVG(\"österreich_(import)_[mwh]_berechnete_auflösungen\") AS \"österreich_import\", AVG(\"frankreich_(export)_[mwh]_berechnete_auflösungen\") AS \"frankreich_export\", AVG(\"frankreich_(import)_[mwh]_berechnete_auflösungen\") AS \"frankreich_import\" FROM smard.allocation WHERE $__timeFilter(datum_von) GROUP BY $__timeGroup(datum_von, $__interval) "
    }
   ]
  },
  {
   "title": "Stromerzeugung ENTSO-E DE_LU (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"index\",$__interval),\n  avg(biomass) as biomass,\n  avg(fossil_hard_coal) as fossil_hard_coal,\n  avg(geothermal) as geothermal,\n  avg(nuclear) as nuclear,\n  avg(\"fossil_brown_coal/lignite\") as \"fossil_brown_coal/lignite\",\n  avg(\"fossil_coal-derived_gas\") as \"fossil_coal-derived_gas\",\n  avg(\"hydro_run-of-river_and_poundage\") as \"hydro_run-of-river_and_poundage\",\n  avg(waste) as waste,\n  avg(hydro_pumped_storage) as storage,\n  avg(solar) as solar,\n  avg(wind_offshore) as wind_offshore,\n  avg(wind_onshore) as wind_onshore,\n  avg(other_renewable) as other_renewable,\n  avg(hydro_water_reservoir) as hydro_water_reservoir,\n  avg(fossil_gas) as fossil_gas\nFROM entsoe.query_generation\nWHERE\n  $__timeFilter(index) AND\n  country = 'DE_LU'\ngroup by 1\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Regelleistung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "dataset": "opendata",
     "rawSql": "SELECT $__timeGroup(datum_von,$__interval), AVG(\"volumen_(+)_[mwh]_berechnete_auflösungen\") AS \"pos_fcr\", AVG(\"volumen_(-)_[mwh]_berechnete_auflösungen\") AS \"neg_fcr\", AVG(\"preis_[€/mwh]_berechnete_auflösungen\") AS \"price\" FROM smard.frequency_reserve WHERE $__timeFilter(datum_von) GROUP BY $__timeGroup(datum_von, $__interval) "
    }
   ]
  }
 ]
}